"use client";
import {useCallback,useEffect,useState} from "react";
import {Copy,RefreshCw,MapPin,Clock3,Check,Radio} from "lucide-react";
import {toast} from "sonner";
import {Toaster} from "@/components/ui/sonner";
import {chinaDate,currentSnapshot,waiting,type PasswordData} from "@/lib/password-model";
export function PasswordSection(){
 const [data,setData]=useState<PasswordData|null>(null);const [loading,setLoading]=useState(false);const [copied,setCopied]=useState<string|null>(null);
 const refresh=useCallback(async()=>{setLoading(true);try{const r=await fetch("/api/passwords",{cache:"no-store"});const result=await r.json() as PasswordData;if(!Array.isArray(result.entries))throw Error("Invalid data");setData(currentSnapshot(result,new Date()))}catch{setData(waiting(new Date(),"暂时无法同步，稍后自动重试"))}finally{setLoading(false)}},[]);
 useEffect(()=>{void refresh();const retry=setInterval(()=>void refresh(),5*60000);const clock=setInterval(()=>{setData(previous=>{if(previous?.fetchedAt&&chinaDate(new Date(previous.fetchedAt))!==chinaDate(new Date()))return waiting(new Date());return previous})},30000);const onFocus=()=>void refresh();window.addEventListener("focus",onFocus);return()=>{clearInterval(retry);clearInterval(clock);window.removeEventListener("focus",onFocus)}},[refresh]);
 const copy=async(id:string,code:string)=>{try{await navigator.clipboard.writeText(code);setCopied(id);toast.success("密码已复制");setTimeout(()=>setCopied(null),1800)}catch{toast.error("复制失败，请手动选择密码")}};
 const view=data??{entries:[{id:"zero-dam",name:"零号大坝"},{id:"layali-grove",name:"长弓溪谷"},{id:"brakkesh",name:"巴克什"},{id:"space-city",name:"航天基地"},{id:"tide-prison",name:"潮汐监狱"},{id:"az3",name:"AZ3"}].map(m=>({...m,code:null,location:""})),fetchedAt:null,sourceDate:null,region:null,status:"pending",error:null,nextUpdateAt:""};
 const time=(s:string)=>new Intl.DateTimeFormat("zh-CN",{timeZone:"Asia/Shanghai",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).format(new Date(s));
 const count=view.entries.filter(x=>x.code).length;
 return <section id="passwords" className="password-section section-shell"><div className="section-label"><span>04 / 每日密码</span><span>DAILY ACCESS CODES</span></div><div className="section-heading"><div><p className="eyebrow">行动前，再确认一次</p><h2>密码在手，<span>开启探索</span></h2></div><button className="refresh-button" disabled={loading} onClick={()=>void refresh()}><RefreshCw size={17} className={loading?"spinning":""}/>{loading?"同步中":"刷新密码"}</button></div>
 <div className="password-status"><span><Radio size={16}/>{loading&&!data?"正在获取密码":count+" / 6 张地图已获取"}</span><span><Clock3 size={16}/>{view.fetchedAt?"获取于 "+time(view.fetchedAt):"今日密码待更新"}</span><span>北京时间 · 每日 02:00 同步</span></div>
 <div className="password-grid">{view.entries.map((entry,i)=><article className={"password-card "+(!entry.code?"is-pending":"")} key={entry.id}><div className="password-card-top"><span>MAP / 0{i+1}</span><span className="code-status">{entry.code?"已获取":"待更新"}</span></div><h3>{entry.name}</h3><div className="access-code"><span>{entry.code??"— — — —"}</span><button disabled={!entry.code} onClick={()=>entry.code&&void copy(entry.id,entry.code)} aria-label={"复制"+entry.name+"密码"}>{copied===entry.id?<Check size={21}/>:<Copy size={21}/>}</button></div><p><MapPin size={15}/>{entry.location||"密码与位置信息待更新"}</p></article>)}</div>
 <div className="source-note"><span>{view.error??(view.sourceDate?"适用日期："+view.sourceDate:"来源未提供密码生效日期；“获取于”是同步时间，出发前请核实。")}</span><span>数据来源：Delta Force Codes</span></div><Toaster position="bottom-right" theme="dark"/></section>;
}