import {sitePath} from "@/lib/site-paths";
import {OperatorSection,WeaponSection} from "./components/archives";
import {ScrollExperience} from "./components/scroll-experience";
import {PasswordSection} from "./components/passwords";
import {HarmonicaSection} from "./components/harmonica";
import {HeroIntroVideo} from "./components/hero-intro-video";
import {OverviewVideo} from "./components/overview-video";
export default function Home(){return <ScrollExperience>
<header className="site-header"><a className="brand" href="#home" aria-label="三角洲行动首页"><img src={sitePath("/assets/logo.png")} alt="三角洲行动"/></a><nav aria-label="页内导航"><a href="#about">游戏介绍</a><a href="#operators">干员档案</a><a href="#weapons">武器库</a><a href="#passwords">每日密码</a><a href="#harmonica">口琴</a></nav><span className="season-tag"><b>S11</b><span>群星赛季 · 国服 PC</span></span></header>
<section className="hero" id="home"><div className="hero-scene"><img className="hero-image" src={sitePath("/assets/hero-clean.png")} alt="三角洲行动干员集结" fetchPriority="high"/><HeroIntroVideo/><div className="hero-grid" aria-hidden="true"/><div className="hero-title"><p className="eyebrow">三角洲行动 · 群星赛季</p><h1>我来陪你玩</h1></div><div className="hero-copy"><p className="hero-subtitle">新一代战术射击 · 搜集物资，协同作战，成功撤离</p><div className="hero-actions"><a className="action action-primary" href="#operators">查看干员</a><a className="action" href="#weapons">查看枪械</a><a className="action" href="#passwords">今日密码</a></div></div><div className="hero-footer"><span>G.T.I. / 战术行动档案</span><a href="#about">向下探索 <i/></a><span>01 / 06</span></div><div className="hero-cover-shade" aria-hidden="true"/></div></section>
<section id="about" className="about section-shell"><div className="section-label"><span>01 / 游戏介绍</span><span>TACTICAL EXTRACTION</span></div><div className="about-grid"><OverviewVideo/><div className="about-content"><p className="eyebrow">烽火地带 · 战术撤离模式</p><h2>搜。打。撤。<br/><em>满载而归。</em></h2><p className="about-summary">带上装备，与队友进入战区，搜索情报和物资，在交战中争取收益，并完成撤离。</p><div className="game-loop"><div><b>01</b><div><h3>兵种搭配</h3><p>四大兵种组成三人小队，搭配各自的战术道具与装备，协同完成行动。</p></div></div><div><b>02</b><div><h3>曼德尔砖</h3><p>争夺并破译高价值物资，有机会获得稀有物品；携带时，位置会向所有小队暴露。</p></div></div><div><b>03</b><div><h3>安全撤离</h3><p>与队友抵达撤离点，将物资带出战区，探索多种特殊撤离方式。</p></div></div></div></div></div></section>
<OperatorSection/><WeaponSection/><PasswordSection/><HarmonicaSection/><footer className="site-footer"><a href="#home">DELTA FORCE / 三角洲行动</a><p>非官方玩家资料页 · S11 STARS</p><a href="#home">返回顶部</a></footer></ScrollExperience>}
