type Voice={midi:number;osc:OscillatorNode;noise:AudioBufferSourceNode;filter:BiquadFilterNode;breath:BiquadFilterNode;envelope:GainNode;lfo:OscillatorNode;vibrato:GainNode;started:number};
export class HarmonicaEngine{
 context:AudioContext|null=null;private master:GainNode|null=null;private wave:PeriodicWave|null=null;private noiseBuffer:AudioBuffer|null=null;private voices=new Map<string,Voice>();private requested=new Map<string,number>();shift=0;volume=.6;
 async activate(){if(!this.context){const context=new AudioContext({latencyHint:"interactive"});this.context=context;this.master=context.createGain();this.master.gain.value=this.volume*.65;const compressor=context.createDynamicsCompressor();compressor.threshold.value=-18;compressor.knee.value=15;compressor.ratio.value=5;compressor.attack.value=.003;compressor.release.value=.12;this.master.connect(compressor);compressor.connect(context.destination);const harmonics=[0,1,.616,.153,.061,.557,.282,.091,.163,.726,.08,.12,.149,.15,.043,.149,.118];this.wave=context.createPeriodicWave(new Float32Array(harmonics.length),new Float32Array(harmonics));this.noiseBuffer=context.createBuffer(1,context.sampleRate,context.sampleRate);const samples=this.noiseBuffer.getChannelData(0);for(let i=0;i<samples.length;i++)samples[i]=(Math.random()*2-1)*.018}if(this.context.state==="suspended")await this.context.resume();if(this.context.state!=="running")throw new Error("浏览器尚未启用声音，请点击开始演奏")}
 setVolume(percent:number){this.volume=percent/100;if(this.context&&this.master)this.master.gain.setTargetAtTime(this.volume*.65,this.context.currentTime,.02)}
 async press(id:string,midi:number){if(this.requested.has(id))return;this.requested.set(id,midi);await this.activate();if(!this.requested.has(id)||!this.context||!this.master||!this.wave||!this.noiseBuffer)return;const context=this.context,t=context.currentTime,frequency=440*Math.pow(2,(midi+this.shift-69)/12);const osc=context.createOscillator();osc.setPeriodicWave(this.wave);osc.frequency.value=frequency;const filter=context.createBiquadFilter();filter.type="lowpass";filter.frequency.value=Math.min(8500,frequency*13);filter.Q.value=.45;const envelope=context.createGain();envelope.gain.setValueAtTime(0,t);for(const [time,gain] of [[.012,.025],[.16,.055],[.8,.09],[1.6,.135],[2.6,.19],[3.6,.24]])envelope.gain.linearRampToValueAtTime(gain,t+time);osc.connect(filter);filter.connect(envelope);envelope.connect(this.master);const noise=context.createBufferSource();noise.buffer=this.noiseBuffer;noise.loop=true;const breath=context.createBiquadFilter();breath.type="bandpass";breath.frequency.value=1800;breath.Q.value=.8;noise.connect(breath);breath.connect(envelope);const lfo=context.createOscillator();lfo.frequency.value=5.1;const vibrato=context.createGain();vibrato.gain.setValueAtTime(0,t);vibrato.gain.linearRampToValueAtTime(3.2,t+.4);lfo.connect(vibrato);vibrato.connect(osc.detune);osc.start(t);noise.start(t);lfo.start(t);this.voices.set(id,{midi,osc,noise,filter,breath,envelope,lfo,vibrato,started:t})}
 release(id:string){this.requested.delete(id);const v=this.voices.get(id);if(!v||!this.context)return;const t=this.context.currentTime;v.envelope.gain.cancelAndHoldAtTime(t);v.envelope.gain.exponentialRampToValueAtTime(.0001,t+.055);v.osc.stop(t+.065);v.noise.stop(t+.065);v.lfo.stop(t+.065);v.osc.onended=()=>{v.osc.disconnect();v.noise.disconnect();v.filter.disconnect();v.breath.disconnect();v.envelope.disconnect();v.lfo.disconnect();v.vibrato.disconnect()};this.voices.delete(id)}
 retune(shift:number){this.shift=shift;if(!this.context)return;for(const v of this.voices.values()){const f=440*Math.pow(2,(v.midi+shift-69)/12);v.osc.frequency.setTargetAtTime(f,this.context.currentTime,.006);v.filter.frequency.setTargetAtTime(Math.min(8500,f*13),this.context.currentTime,.01)}}
 stopAll(){for(const id of [...this.requested.keys()])this.release(id);this.retune(0)}
 close(){this.stopAll();void this.context?.close()}
}